# Generated by Django 5.1 on 2024-08-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='profile_pic',
            field=models.ImageField(blank=True, default='https://static.vecteezy.com/system/resources/thumbnails/020/765/399/small/default-profile-account-unknown-icon-black-silhouette-free-vector.jpg', upload_to='profile_pics/'),
        ),
    ]
