# Generated by Django 5.1 on 2024-08-23 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_manage', '0002_course_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='profile_pic',
            new_name='course_image',
        ),
    ]
