# Generated by Django 5.1 on 2024-08-23 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_manage', '0004_alter_topic_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='course_manage.topic'),
        ),
    ]
