# Generated by Django 5.1 on 2024-08-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_manage', '0005_alter_video_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='pdf_file',
            field=models.FileField(null=True, upload_to='pdfs/'),
        ),
    ]
