# Generated by Django 5.1 on 2024-08-23 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_manage', '0006_topic_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='pdf_file',
        ),
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='course_manage.topic')),
            ],
        ),
    ]
