# Generated by Django 5.1.1 on 2024-10-31 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_manage', '0008_remove_course_course_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='company_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='course_manage.companysettings'),
        ),
    ]
