# Generated by Django 5.1 on 2024-08-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_manage', '0012_rename_student_id_answer_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
